# -*- coding: utf-8 -*-
"""
/***************************************************************************
 savpqgis
                                 A QGIS plugin
 Este es un plugin para automatizar procesos del proyeto anillo vial periférico
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-11
        copyright            : (C) 2020 by Luis Antony Meza
        email                : lmeza@mtc.gob.pe
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load savpqgis class from file savpqgis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .savpqgis import savpqgis
    return savpqgis(iface)
